/** Quality profiles for the verified moonlit-alpine grade. */
export { WolfhourGrade as WolfhourPost } from './wolfhour-grade.js';

export const WOLFHOUR_POST_PROFILES = Object.freeze({
    Minimal: Object.freeze({
        enabled: false,
        profile: 'off',
        useFilmGrain: false,
        silverTintStrength: 0.0,
        bloomDownsample: 0.56,
        ditherStrength: 0.0012,
        bloomRadius: 0.5,
        bloomThreshold: 0.25,
        tintDesaturation: 0.55,
        vignetteOffset: 1.18,
        vignetteDarkness: 0.58,
        exposure: 1.0,
        contrast: 1.03,
        saturation: 0.25,
        grainStrength: 0.0,
    }),
    Low: Object.freeze({
        enabled: false,
        profile: 'off',
        useFilmGrain: false,
        silverTintStrength: 0.0,
        bloomDownsample: 0.58,
        ditherStrength: 0.0012,
        bloomRadius: 0.5,
        bloomThreshold: 0.25,
        tintDesaturation: 0.55,
        vignetteOffset: 1.18,
        vignetteDarkness: 0.58,
        exposure: 1.0,
        contrast: 1.03,
        saturation: 0.25,
        grainStrength: 0.0,
    }),
    Medium: Object.freeze({
        enabled: true,
        profile: 'balanced',
        useFilmGrain: false,
        silverTintStrength: 0.08,
        bloomDownsample: 0.58,
        ditherStrength: 0.0014,
        bloomRadius: 0.52,
        bloomThreshold: 0.45,
        tintDesaturation: 0.52,
        vignetteOffset: 1.18,
        vignetteDarkness: 0.56,
        exposure: 1.0,
        contrast: 1.03,
        saturation: 0.25,
        grainStrength: 0.0,
    }),
    High: Object.freeze({
        enabled: true,
        profile: 'full',
        useFilmGrain: false,
        silverTintStrength: 0.18,
        bloomDownsample: 0.58,
        ditherStrength: 0.0018,
        bloomRadius: 0.54,
        bloomThreshold: 0.42,
        tintDesaturation: 0.56,
        vignetteOffset: 1.18,
        vignetteDarkness: 0.58,
        exposure: 1.0,
        contrast: 1.04,
        saturation: 0.25,
        grainStrength: 0.00135,
    }),
    Ultra: Object.freeze({
        enabled: true,
        profile: 'full',
        useFilmGrain: false,
        silverTintStrength: 0.21,
        bloomDownsample: 0.61,
        ditherStrength: 0.002,
        bloomRadius: 0.56,
        bloomThreshold: 0.40,
        tintDesaturation: 0.57,
        vignetteOffset: 1.2,
        vignetteDarkness: 0.6,
        exposure: 1.0,
        contrast: 1.04,
        saturation: 0.25,
        grainStrength: 0.00145,
    }),
    Extreme: Object.freeze({
        enabled: true,
        profile: 'full',
        useFilmGrain: false,
        silverTintStrength: 0.24,
        bloomDownsample: 0.64,
        ditherStrength: 0.0022,
        bloomRadius: 0.58,
        bloomThreshold: 0.38,
        tintDesaturation: 0.58,
        vignetteOffset: 1.22,
        vignetteDarkness: 0.62,
        exposure: 1.0,
        contrast: 1.04,
        saturation: 0.25,
        grainStrength: 0.00155,
    }),
});

export function getWolfhourPostProfile(qualityName) {
    const key = typeof qualityName === 'string' ? qualityName : 'High';
    const profile = WOLFHOUR_POST_PROFILES[key] || WOLFHOUR_POST_PROFILES.High;
    return { ...profile };
}
